# Generated by Django 4.2.16 on 2024-11-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_certificationpost_price_purchasedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='myapp.certificationpost')),
            ],
        ),
    ]
