# Generated by Django 4.2.16 on 2024-11-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_practiceexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='course_highlights',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='course_requirements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='join_today',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='what_you_will_gain',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='who_should_take_this_course',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='why_this_course_stands_out',
            field=models.TextField(null=True),
        ),
    ]
