# Generated by Django 4.2.16 on 2024-11-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_certificationpost_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
