# Generated by Django 4.2.16 on 2024-11-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_certificationpost_image_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='difficulty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='exam_format',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
