# Generated by Django 4.2.16 on 2024-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_certificationpost_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='number_of_practices',
            field=models.IntegerField(default=4),
        ),
    ]
