# Generated by Django 4.2.16 on 2024-11-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_certificationpost_number_of_practices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('kr', 'Korean'), ('jp', 'Japanese'), ('cn', 'Chinese'), ('ru', 'Russian'), ('pt', 'Portuguese'), ('it', 'Italian'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('ms', 'Malay'), ('id', 'Indonesian'), ('vi', 'Vietnamese'), ('tr', 'Turkish'), ('th', 'Thai'), ('nl', 'Dutch'), ('pl', 'Polish'), ('sv', 'Swedish'), ('no', 'Norwegian'), ('da', 'Danish'), ('fi', 'Finnish'), ('el', 'Greek'), ('he', 'Hebrew')], default='en', max_length=2),
        ),
    ]
