# Generated by Django 4.2.16 on 2024-11-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_certificationpost_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationpost',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('kr', '한국어'), ('jp', '日本語'), ('cn', '中文'), ('ru', 'Русский'), ('pt', 'Português'), ('it', 'Italiano'), ('hi', 'हिन्दी'), ('ar', 'العربية'), ('bn', 'বাংলা'), ('ms', 'Bahasa Melayu'), ('id', 'Bahasa Indonesia'), ('vi', 'Tiếng Việt'), ('tr', 'Türkçe'), ('th', 'ไทย'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('sv', 'Svenska'), ('no', 'Norsk'), ('da', 'Dansk'), ('fi', 'Suomi'), ('el', 'Ελληνικά'), ('he', 'עברית')], default='en', max_length=2),
        ),
    ]
