# Generated by Django 4.2.16 on 2024-11-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_certificationpost_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='num_tests',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='time_limit',
            field=models.IntegerField(default=1800),
        ),
    ]
