# Generated by Django 4.2.16 on 2024-11-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
