# Generated by Django 4.2.16 on 2024-11-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_post_content_post_html_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationpost',
            name='time_limit',
            field=models.IntegerField(default=90),
        ),
    ]
