# Generated by Django 4.2.16 on 2024-11-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_practiceexam_exam_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedcourse',
            name='completed_exams',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='UserExamProgress',
        ),
    ]
