# Generated by Django 4.2.16 on 2024-11-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_purchasedcourse_completed_exams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveIntegerField()),
                ('json_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='myapp.certificationpost')),
            ],
            options={
                'ordering': ['test_number'],
                'unique_together': {('certification_post', 'test_number')},
            },
        ),
        migrations.DeleteModel(
            name='PracticeExam',
        ),
    ]
