# Generated by Django 4.2.16 on 2024-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_certificationtest_delete_practiceexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='practice_exam_translate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='review_mode_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificationpost',
            name='timed_mode_description',
            field=models.TextField(null=True),
        ),
    ]
