# Generated by Django 4.2.16 on 2024-12-01 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_certificationpost_default_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationpost',
            name='passing_score',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
